apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-tester-4335
  namespace: anotherclass-433
spec:
  selector:
    matchLabels:
      instance: api-tester-4335
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        instance: api-tester-4335
    spec:
      nodeSelector:
        zone: b-team
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: instance
                      operator: In
                      values: [api-tester-4335]
                topologyKey: "zone"
      containers:
        - name: api-tester4335
          image: songju021/api-tester:3.0.0
          resources:
            requests:
              memory: "100Mi"
              cpu: "100m"
            limits:
              memory: "200Mi"
              cpu: "200m"
