apiVersion: v1
kind: Service
metadata:
  namespace: anotherclass-433
  name: api-tester-4335
spec:
  selector:
    instance: api-tester-4335
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30335
  type: LoadBalancer
