apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: anotherclass-433
  name: api-tester-4331
spec:
  selector:
    matchLabels:
      instance: api-tester-4331
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        instance: api-tester-4331
    spec:
      nodeSelector:
        zone: b-team
      containers:
        - name: api-tester-4331
          image: songju021/api-tester:3.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http
          resources:
            requests:
              memory: "100Mi"
              cpu: "100m"
            limits:
              memory: "200Mi"
              cpu: "200m"
